name: 💅 Visual Regression Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  visual-regression-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Use NodeJS 18'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: 'Install project dependencies'
        run: npm install

      - name: 'Build Storybook'
        run: npm run build-storybook

      - name: 'Start Storybook server'
        run: |
          npm run storybook &
          sleep 5

      - name: 'Wait for Storybook server to be ready'
        run: |
          timeout 60 bash -c "until curl -s http://localhost:6006; do echo 'Waiting for server...'; sleep 2; done"

      - name: 'Run Visual Regression Tests'
        run: npm run test:visual

      - name: 'Upload BackstopJS Results'
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: backstopjs-visual-test-results
          path: visual-tests/visual_images_test/
